includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DeepEMD.yaml
  - backbones/resnet12.yaml

seed: 1
pretrain_path: ./results/DeepEMDPretrain-miniImageNet--ravi-resnet12-5-1-Jan-15-2025-14-26-11/checkpoints/emb_func_best.pth
train_episode: 100
test_episode: 600 # 源代码是5000，val是1000
workers: 8 # number of workers for dataloader in all threads
dataloader_num: 2
persistent_workers: True  # 保持worker进程
deterministic: False
episode_size: 1

optimizer:
  name: SGD
  kwargs:
    lr: 0.0005
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

lr_scheduler:
  name: StepLR
  kwargs:
    step_size: 10
    gamma: 0.5