includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DeepEMD_pretrain.yaml
  - backbones/resnet12.yaml

seed: 1
# pretrain_path: ./results/DeepEMD_Pretrain-miniImageNet--ravi-resnet12/checkpoints/emb_func_best.pth
test_episode: 600 # 源代码是5000，val是1000
epoch: 100

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

lr_scheduler:
  name: StepLR
  kwargs:
    step_size: 20
    gamma: 0.2