includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DeepEMD.yaml
  - backbones/resnet12.yaml

seed: 1 # maybe in reproduce?
pretrain_path: null
test_episode: 600 # 源代码是5000，val是1000

optimizer:
  name: SGD
  kwargs:
    lr: 0.0005
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

lr_scheduler:
  name: StepLR
  kwargs:
    step_size: 10
    gamma: 0.5