includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DeepEMD_pretrain.yaml
  - backbones/resnet12.yaml


data_root: /data/miniImageNet--ravi # 应该是吧
image_size: 84

episode_size: 100
epoch: 120
batch_size: 128 # 对应源代码pretrain的bs=128
test_episode: 100   # 论文里好像没说？
test_epoch: 100 # 源代码是每训练完1个epoch就测试一次，暂时这么设置
test_query: 15 # 源代码中验证时使用的args.query=15
test_shot: 1
test_way: 5
train_episode: 1000  # ?
query_num: 15
shot_num: 1
way_num: 5

n_gpu: 1
device_ids: 1
seed: 1

backbone:
  name: ResNet12
  kwargs:
    reduce_dim: 640

optimizer: # 对应源代码pretrain的optimizer, 按照默认值来的
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

classifier:
  name: DeepEMDPretrain
  kwargs:
    feat_dim: 640
    num_class: 64 # 预训练类别数
    # SFC参数
    sfc_lr: 0.1
    sfc_update_step: 100
    sfc_bs: 4
    # Solver参数
    form: QP
    l2_strength: 0.0001
    solver: opencv # ?

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.2
    step_size: 30

save_part: # ?
  - emb_func
  - classifier